language: node_js
before_install:
- nvm install stable
- node -v
- npm -v
- npm install -g gulp
- npm install gulp
- npm install gulp-typescript
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: NCNOPz3vBbARrUCON+u3aXwDnQmH9UfLiPWse+fODF7FpRI/IyVVzjJ5v+GIg+oCSdwBzE4CLKVSe4RBspvu2VaHcagIhRnipRw5EMpdff4U0lfVgNeSbGMnQqloaIe8anzasgTEip6QXKJ5v87ukq85q0sNxjwtkZpCUyjKFQ2SeGV+2fgVp5AIeCYShwvnV37jDyz9s4fjB9Sv+MtA6w59O4012iQPnIdwwdJxUE+BZOEQ9Pek+9zDdI3Zfcq/rhgJ6sGGzYym639GIfFyy8hBjwaWfWHJXFPNnDVEggBPJB2PuCZVUKwGW+9J6w6UgcL/xtc+KSAwtV8rBvc0DgHKEQD9SNZL6xivzSD+UQZOkC1/Lp3is5lOJiKathLFymSbb/LtWBDLdg6+wtRYZg7QxoqIr/xEKwqzhejsg/iI/teXdfMqsZKMklCgNn48PxaDTLDm9cFVK1hLhXK4NdLEYfffEIWOx4WGqps16OujPhQvO6r9HVYW5quLnZIlQeBkhQ9cSgL7pVFY2YxTSLglKbX8Rvg7Udd+1gYWUGO9Ez7Bw/+Yf8WLSBG+7siLtyH5CY9tpdZoxRjEvkZV9VQIyqwggpQ6bIJuYGfNolIG6zYMyx0qvROLnpe3BEHoEVwT1xEON+Dkjsu6EO9piyU76wD3jBNQkYtLO8L3ySY=
  on:
    tags: true
    repo: UmbrellaZone/gulp-umbrella
notifications:
  slack:
    secure: C+gLjTOdmIjJ+vwb/N5HyWIxXOJVtEu3e4X8k9vjfOnAXPZAnMwx3JVFGQxKz7PGcr49taYm2uDUGL7lRmYvj0zGy36Kadgc3lHBn+Cf0JL47VIrP2aVwf5DIfXJoVx7Fx3gFv59MFrcsoEqOg2g6lP1kzMBGiMo2zKz46nMnSfTG/ztIct373r3PtucRbCotg6OQcDXNsdgTJFdx1tsgRbno/1+XEJeoMpPNofUjTozwwPWAeimSUKkrtD0vYoqetz+mUuWVuha9+zEqt9TcF5pCxYAP1YYw4l6RVEi3hxOK176tDy2SwqEEZM4OGQg1cP1Cw08X0pQXHCg55JPnDWJeAk3TsckxrhNb65C5GOwRP+luM3+8sFzEvg/f1aGVmuAwMJsiNOB4arlT0fwtQQmLCbYvWSUsj5m9lVHpYy2ttz8DI/dYHdShqKdXq4TEHrFjYCU8/S68YnwS9vJ8Twfl/96SK+sUwy4c/jrXzYflTHZFJ5UbovNzcbvlNCm2XuUPLQ+YKp3OxWI5bEqDn4i3zJVEMmLA1c46ueQmt7m6lkWkWqvqRlNyr+HdzyArZi2BiWMgIiQlygYwPOH0Z+DhIt8UCjOqtqpg4uzMYssM3lQb3Gr2PRMihw2TzCTAuBDr4jOFQ9C0KxtM1+4EldYVjo+XXrBOA/EeUi3WN8=
